#------------------------------------------------------------------------------
# FILE:         action.yaml
# CONTRIBUTOR:  Jeff Lill
# COPYRIGHT:    Copyright (c) 2005-2021 by neonFORGE LLC.  All rights reserved.
#
# The contents of this repository are for private use by neonFORGE, LLC. and may not be
# divulged or used for any purpose by other organizations or individuals without a
# formal written and signed agreement with neonFORGE, LLC.

#------------------------------------------------------------------------------
# Runs unit tests for the Release configuration within a neonFORGE repo and then
# uploads the test output as a workflow artifact.
#
# NOTE:
#
# This action is intended to be used after a code build has been performed in
# the same workflow job.

name: test
description: "Runs unit tests within a neonFORGE repo and uploads the results as a workflow artifact"
inputs:
  repo:
    description: "Specifies the repository to be tested, one of: 'neonCLOUD', 'neonKUBE', or 'neonLIBRARY'"
    required: true
  filter:
    description: "Optionally specifies a test trait filter"
    required: false
    default: ""
  results-folder:
    description: "Specifies the folder where test result files will be copied on the runner"
    required: true
outputs:
  success:
    description: "Returns 'true' when all tests passed (or were skipped) or 'false' when some tests failed"
  result-uris:
    description: "Returns as a semicolon separated list of markdown formatted URIs to each test result"
  result-info:
    description: "Returns as a semicolon separated list of test summary information for each test result.  Each summary is formatted like 'name,#tests,#errors,#skips,elapsed'.  The summarys are in the same order as the [result-uris] links"
runs:
  using: node12
  main: action.js
